### ISSUE TITLE
Webpage

### ISSUE THREAD

**Issue by tfuerholzer** [rstropek-teaching/pokelist-quiz-4ahif-tfuerholzer#1]
Webpage can be seen under : https://tfuerholzer.github.io/pokemons/main.html

**Comment by rstropek** [comment]
@tfuerholzer Thank you for your homework. Very colorful solution ;-) Works as expected. Your extra point is secured.

I saw that you included two different versions of jQuery. Is there a special reason for that? If not, avoid that. I makes your website unnecessarily large.

Greetings,
Rainer Stropek
